services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: koa-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend/src:/app/src
      - ./backend/tsconfig.json:/app/tsconfig.json
      - ./backend/package.json:/app/package.json
      - ./backend/dist:/app/dist
    command: sh -c "chown -R $(id -u):$(id -g) /app/dist && npm run dev"
    restart: unless-stopped
