services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: koa-backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=appdb
    volumes:
      - ./backend/src:/app/src
      - ./backend/tsconfig.json:/app/tsconfig.json
      - ./backend/package.json:/app/package.json
      - ./backend/dist:/app/dist
    command: sh -c "chown -R $(id -u):$(id -g) /app/dist && npm run dev"
    restart: unless-stopped
    depends_on:
      - postgres
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/config/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  postgres_data:
